#!/usr/bin/env python3
"""Paper Figure 7: long-molecule XTP decline and its rescue by IKT.

Input is one record file written by `ikt_eval_big.py --out <recs.json>`, i.e. a
single dataset generated by the frozen ADT generator with the frozen IKT
corrector attached. Both curves are read from the *same* molecules, binned in
3-atom bins of heavy-atom count:

  ADT alone     = fraction with raw == True
  ADT + IKT     = fraction with raw OR rescued_at <= MAXIT   (default 6 xTB calls)

Left axis: XTP (%) with Wilson 95% confidence intervals.
Right axis: the number of molecules in each bin (the n the intervals come from).

Usage:
  python3 plot_ikt_xtp_size.py --recs persize_ikt.json --out ikt_xtp_size.pdf
"""
import argparse, json, math
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def wilson(k, n, z=1.96):
    """Wilson score interval; returns (center_pct, err_lo_pct, err_hi_pct) about p=k/n."""
    if n == 0:
        return (0.0, 0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    lo, hi = max(0.0, c - h), min(1.0, c + h)
    return (100 * p, max(0.0, 100 * (p - lo)), max(0.0, 100 * (hi - p)))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--recs", required=True,
                    help="record JSON from ikt_eval_big.py --out (key 'recs')")
    ap.add_argument("--out", default="ikt_xtp_size.pdf",
                    help="output figure path (.pdf or .png; default: %(default)s)")
    ap.add_argument("--maxit", type=int, default=6,
                    help="count a molecule as rescued if rescued_at <= MAXIT (default: %(default)s)")
    ap.add_argument("--bin", type=int, default=3, help="bin width in heavy atoms (default: %(default)s)")
    ap.add_argument("--lo", type=int, default=21, help="first bin edge (default: %(default)s)")
    ap.add_argument("--hi", type=int, default=56, help="last bin edge (default: %(default)s)")
    ap.add_argument("--min-n", type=int, default=15,
                    help="skip bins with fewer molecules than this (default: %(default)s)")
    args = ap.parse_args()

    recs = json.load(open(args.recs))["recs"]
    na = np.array([r["na"] for r in recs])
    raw = np.array([1 if r["raw"] else 0 for r in recs])
    ikt = np.array([1 if (r["raw"] or (r["rescued_at"] is not None and r["rescued_at"] <= args.maxit))
                    else 0 for r in recs])

    W = args.bin
    edges = np.arange(args.lo, args.hi + W, W)
    cx, adt, ik, ns = [], [], [], []
    adt_lo, adt_hi, ik_lo, ik_hi = [], [], [], []
    for e in edges[:-1]:
        m = (na >= e) & (na < e + W)
        n = int(m.sum())
        if n < args.min_n:
            continue
        cx.append(e + W / 2 - 0.5)
        ns.append(n)
        pa, la, ha = wilson(int(raw[m].sum()), n)
        adt.append(pa); adt_lo.append(la); adt_hi.append(ha)
        pk, lk, hk = wilson(int(ikt[m].sum()), n)
        ik.append(pk); ik_lo.append(lk); ik_hi.append(hk)
    cx = np.array(cx); adt = np.array(adt); ik = np.array(ik)

    fig, ax = plt.subplots(figsize=(10.5, 7.4))
    ax2 = ax.twinx()

    # right axis: molecules per bin -- the n the error bars are computed from
    ax2.bar(cx, ns, width=W, color="#c7d2e6", alpha=0.55, zorder=1)
    ax2.set_ylabel("count", color="#6b7ba0", fontsize=16)
    ax2.tick_params(axis="y", colors="#6b7ba0", labelsize=13)
    ax2.set_ylim(0, max(ns) * 1.25)

    # left axis: XTP curves
    ax.set_zorder(ax2.get_zorder() + 1)
    ax.patch.set_visible(False)
    ax.errorbar(cx, adt, yerr=[adt_lo, adt_hi], color="#1f3b73", lw=3.0, marker="o", ms=7,
                capsize=4, elinewidth=1.6, zorder=5, label="ADT (Wilson 95% CI)")
    ax.errorbar(cx, ik, yerr=[ik_lo, ik_hi], color="#d02020", lw=3.2, marker="s", ms=7,
                capsize=4, elinewidth=1.6, zorder=6, label="ADT+IKT (Wilson 95% CI)")
    for x, a, k, n in zip(cx, adt, ik, ns):
        ax.text(x, a - 4.5, f"{a:.1f}", ha="center", fontsize=11, color="#1f3b73", fontweight="bold")
        ax.text(x, k + 2.2, f"{k:.1f}", ha="center", fontsize=11, color="#a01818", fontweight="bold")

    ax.set_xlabel("heavy-atom count", fontsize=16)
    ax.set_ylabel("XTP (%)", fontsize=16)
    ax.set_title("Long-molecule XTP decline and its rescue by IKT", fontsize=18, fontweight="bold")
    ax.set_xlim(20, 56)
    ax.set_ylim(28, 106)
    ax.tick_params(axis="both", labelsize=13)
    ax.grid(axis="y", alpha=0.25)
    ax.legend(loc="lower left", fontsize=15, framealpha=0.95)

    fig.tight_layout()
    fig.savefig(args.out, dpi=200)
    print("wrote", args.out)
    print(f"{'bin-center':>10} {'n':>5} {'ADT (95%CI)':>18} {'+IKT (95%CI)':>20}")
    for x, a, al, ah, k, kl, kh, n in zip(cx, adt, adt_lo, adt_hi, ik, ik_lo, ik_hi, ns):
        print(f"{x:>10.1f} {n:>5}   {a:>5.1f} -{al:.1f}/+{ah:.1f}      {k:>5.1f} -{kl:.1f}/+{kh:.1f}")


if __name__ == "__main__":
    main()
